### ISSUE TITLE
Limit to mutations only

### ISSUE THREAD

**Issue by aavelyn** [helfer/apollo-link-queue#13]
Is is possible to queue only muatations and not queries?

**Comment by pl12133** [comment]
I think you can write a wrapper that only calls the queue link for mutations:

```js
import { ApolloLink } from 'apollo-link';

function isMutationOperation(operation) {
    return operation.query.definitions.filter((e) => e.operation === 'mutation').length > 0;
}

const queueLink = new QueueLink();

const onlyQueueMutationsLink = new ApolloLink((operation, forward) =>
  isMutationOperation(operation) ? queueLink.request(operation, forward) : forward(operation)
);
```

**Comment by wtrocki** [comment]
I'm happy to write this along with https://github.com/helfer/apollo-link-queue/issues/3. 

Idea will be to be able to pass filter and storage interface to queue. 

```
const queueLink = new QueueLink({store,filter});
``` 

Where filter will be something like

```
(operation, forward) =>
  isMutationOperation(operation) ? queueLink.request(operation, forward) : forward(operation)
)
```

**Comment by wtrocki** [comment]
Done in: https://github.com/helfer/apollo-link-queue/pull/14

**Comment by helfer** [comment]
Thanks for the effort @wtrocki. I like to keep things as simple as possible and separate concerns, so I would recommend using @pl12133 's approach here. The philosophy of apollo link is like the Unix philosophy where each utility is small and limited in scope but input and output can be piped. More complex things can then be done by combining simple links together.
