### ISSUE TITLE
Apollo v3.0

### ISSUE THREAD

**Issue by Svarto** [helfer/apollo-link-queue#20]
Quick q, does this work in Apollo 3.0?

**Comment by helfer** [comment]
I don't know, I haven't tried. I'm going to update the dependencies to import from @apollo/client and release a new version anyway.

**Comment by helfer** [comment]
Published 3.0.0, which should work with Apollo Client 3.0 out of the box. Let me know if it doesn't.

**Comment by alew97** [comment]
@helfer @Svarto The latest version of this package according to yarn is 2.2.0. Were you able to get v3.0.0 and does it work with Apollo v3.0? Please help 😭

**Comment by helfer** [comment]
@alew97 not sure why it's not working for you. According to NPM 3.0 was published properly: https://www.npmjs.com/package/apollo-link-queue
I've personally tested with Apollo 3.0, so I'm sure it's working.
